### ISSUE TITLE
Mod compatibility bug on servers?

### ISSUE THREAD

**Issue by MSandro** [Dunkmania101/SpatialHarvesters#47]
Hello, I have installed a server based on the [Sky Fabrication Modpack](https://www.curseforge.com/minecraft/modpacks/sky-fabrication/files/3363637), and there Crafting Station Slabs ([Improved Stations Mod](https://www.curseforge.com/minecraft/mc-mods/improved-stations/files/3032328)) turns in Soil Harvester 8 when placed :)

There is currently no official server file released for the modpack, but maybe you can try to reproduce this on a fabric server with Improved Stations and Spatial Harvesters. I am not sure which mod causes this weird issue.

**Comment by MSandro** [comment]
The following snippet was generated in the latest.log on my client:
```
[17:01:14] [main/FATAL]: Error executing task on Client
java.lang.ClassCastException: dunkmania101.spatialharvesters.objects.tile_entities.LootHarvesterTE cannot be cast to me.shedaniel.istations.blocks.entities.CraftingStationBlockEntity
	at me.shedaniel.istations.ImprovedStations.lambda$static$0(ImprovedStations.java:48) ~[improved-stations-2.0.3.jar:?]
	at me.shedaniel.istations.ImprovedStations$$Lambda$1915/1791285768.create(Unknown Source) ~[?:?]
	at net.fabricmc.fabric.impl.screenhandler.ExtendedScreenHandlerType.create(ExtendedScreenHandlerType.java:44) ~[1f12952a-3913-48a8-845f-78933b1e941b.jar:?]
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.openScreen(ClientNetworking.java:80) ~[1f12952a-3913-48a8-845f-78933b1e941b.jar:?]
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.lambda$onInitializeClient$0(ClientNetworking.java:54) ~[1f12952a-3913-48a8-845f-78933b1e941b.jar:?]
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking$$Lambda$11716/1024349092.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1015) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
```
sometimes a Loot Harvester was placed :)

**Comment by MSandro** [comment]
okay I think this is not a problem caused by Spatial Harvesters, I am currently not sure which mod is causing this.
