### ISSUE TITLE
port this to 1.18

### ISSUE THREAD

**Issue by Chuunkyz** [Dunkmania101/SpatialHarvesters#54]
_I saw a modpack that was using that version in 1.18 and assumed it would work. I'll remove those tags and release new jars at some point. Thanks for letting me know!_

I'm the author of this modpack, and you mod isn't 100% functional at all in 1.18
plus the fact that i had to override the dependencies to make it work

here's a crash on a server using my modpack :

java.lang.NoSuchMethodError: 'net.minecraft.class_2487 net.minecraft.class_2586.method_11007(net.minecraft.class_2487)'
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.2)
	at dunkmania101.spatialharvesters.objects.blocks.base.PreservedDataCustomHorizontalShapedBlock.onUse(PreservedDataCustomHorizontalShapedBlock.java:83)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:937)
	at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:327)
	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1057)
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30)
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8)
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21)
	at net.minecraft.server.ServerTask.run(ServerTask:18)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151)
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:780)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:162)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125)
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:762)
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134)
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:741)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:688)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:833)

**Comment by Dunkmania101** [comment]
I thought that jar would work in 1.18 because I saw it was listed in your pack. That's a feedback loop of confusion!

Anyway, I'm trying to get to a build that'll launch but it keeps complaining about a nonexistent method being called by a library. I'm working on it.

**Comment by Dunkmania101** [comment]
I released two new jars, one for 1.17.x and one for 1.18.x, both labeled as 0.11.12d. Please let me know if something's still broken!
