### ISSUE TITLE
Crash with Newer Fabric API

### ISSUE THREAD

**Issue by kadir1243** [Dunkmania101/SpatialHarvesters#58]
With this [pull](https://github.com/FabricMC/fabric/pull/1989) mod crashes with 
	Suppressed: java.lang.NoClassDefFoundError: dunkmania101.spatialharvesters.init.BlockInit (initialization failure)
		at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:134)
		at java.lang.Class.forNameImpl(Native Method)
		at java.lang.Class.forName(Class.java:422)
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 21 more
	Caused by: java.lang.NoClassDefFoundError: net.fabricmc.fabric.api.tool.attribute.v1.FabricToolTags
		at dunkmania101.spatialharvesters.init.BlockInit.getMetalBlockSettings(BlockInit.java:175)
		at dunkmania101.spatialharvesters.init.BlockInit.<clinit>(BlockInit.java:21)
		at dunkmania101.spatialharvesters.init.ItemInit.<clinit>(ItemInit.java:60)
		... 27 more
	Suppressed: java.lang.NoClassDefFoundError: dunkmania101.spatialharvesters.init.BlockInit (initialization failure)
		at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:134)
		at dunkmania101.spatialharvesters.init.BlockEntityInit.<clinit>(BlockEntityInit.java:25)
		at java.lang.Class.forNameImpl(Native Method)
		at java.lang.Class.forName(Class.java:422)
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 21 more
	Caused by: java.lang.NoClassDefFoundError: net.fabricmc.fabric.api.tool.attribute.v1.FabricToolTags
		at dunkmania101.spatialharvesters.init.BlockInit.getMetalBlockSettings(BlockInit.java:175)
		at dunkmania101.spatialharvesters.init.BlockInit.<clinit>(BlockInit.java:21)
		at dunkmania101.spatialharvesters.init.ItemInit.<clinit>(ItemInit.java:60)
		... 27 more

**Comment by Dunkmania101** [comment]
Should be fixed with DelilahEve's PR.
